context:
  version: 0.4.0

package:
  name: htmlq
  version: ${{ version }}

source:
  url: https://github.com/mgdm/htmlq/archive/v${{ version }}.tar.gz
  sha256: c2954c0fcb3ada664b14834646aa0a2c4268683cc51fd60d47a71a9f7e77d4b9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - htmlq --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Uses CSS selectors to extract bits content from HTML files
  homepage: https://github.com/mgdm/htmlq
  repository: https://github.com/mgdm/htmlq

extra:
  recipe-maintainers:
    - danielnachun
